/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCatalogRouteImport } from './routes/_app/catalog'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppPatientsIndexRouteImport } from './routes/_app/patients/index'
import { Route as AppPatientsPatientIdRouteImport } from './routes/_app/patients/$patientId'
import { Route as AppVisitsIndexRouteImport } from './routes/_app/visits/index'
import { Route as AppVisitsVisitIdRouteImport } from './routes/_app/visits/$visitId'
import { Route as AppAdminTenantsIndexRouteImport } from './routes/_app/admin/tenants/index'
import { Route as AppAdminTenantsTenantIdRouteImport } from './routes/_app/admin/tenants/$tenantId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRoute,
} as any)
const AppPatientsPatientIdRoute = AppPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsIndexRoute = AppVisitsIndexRouteImport.update({
  id: '/visits/',
  path: '/visits/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisitsVisitIdRoute = AppVisitsVisitIdRouteImport.update({
  id: '/visits/$visitId',
  path: '/visits/$visitId',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsIndexRoute = AppAdminTenantsIndexRouteImport.update({
  id: '/admin/tenants/',
  path: '/admin/tenants/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminTenantsTenantIdRoute = AppAdminTenantsTenantIdRouteImport.update({
  id: '/admin/tenants/$tenantId',
  path: '/admin/tenants/$tenantId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/catalog': typeof AppCatalogRoute
  '/settings': typeof AppSettingsRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/visits/$visitId': typeof AppVisitsVisitIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/visits/': typeof AppVisitsIndexRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/tenants/': typeof AppAdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/catalog': typeof AppCatalogRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/visits/$visitId': typeof AppVisitsVisitIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/patients': typeof AppPatientsIndexRoute
  '/visits': typeof AppVisitsIndexRoute
  '/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/admin/tenants': typeof AppAdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/catalog': typeof AppCatalogRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/patients/$patientId': typeof AppPatientsPatientIdRoute
  '/_app/visits/$visitId': typeof AppVisitsVisitIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_app/visits/': typeof AppVisitsIndexRoute
  '/_app/admin/tenants/$tenantId': typeof AppAdminTenantsTenantIdRoute
  '/_app/admin/tenants/': typeof AppAdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalog'
    | '/settings'
    | '/patients/$patientId'
    | '/visits/$visitId'
    | '/admin/'
    | '/patients/'
    | '/visits/'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/catalog'
    | '/settings'
    | '/'
    | '/patients/$patientId'
    | '/visits/$visitId'
    | '/admin'
    | '/patients'
    | '/visits'
    | '/admin/tenants/$tenantId'
    | '/admin/tenants'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/catalog'
    | '/_app/settings'
    | '/_app/'
    | '/_app/patients/$patientId'
    | '/_app/visits/$visitId'
    | '/_app/admin/'
    | '/_app/patients/'
    | '/_app/visits/'
    | '/_app/admin/tenants/$tenantId'
    | '/_app/admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog': {
      id: '/_app/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/patients/$patientId': {
      id: '/_app/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AppPatientsPatientIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits/': {
      id: '/_app/visits/'
      path: '/visits'
      fullPath: '/visits/'
      preLoaderRoute: typeof AppVisitsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/visits/$visitId': {
      id: '/_app/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/visits/$visitId'
      preLoaderRoute: typeof AppVisitsVisitIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/': {
      id: '/_app/admin/tenants/'
      path: '/admin/tenants'
      fullPath: '/admin/tenants/'
      preLoaderRoute: typeof AppAdminTenantsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/tenants/$tenantId': {
      id: '/_app/admin/tenants/$tenantId'
      path: '/admin/tenants/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AppAdminTenantsTenantIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCatalogRoute: typeof AppCatalogRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPatientsPatientIdRoute: typeof AppPatientsPatientIdRoute
  AppVisitsVisitIdRoute: typeof AppVisitsVisitIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
  AppVisitsIndexRoute: typeof AppVisitsIndexRoute
  AppAdminTenantsTenantIdRoute: typeof AppAdminTenantsTenantIdRoute
  AppAdminTenantsIndexRoute: typeof AppAdminTenantsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCatalogRoute: AppCatalogRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppPatientsPatientIdRoute: AppPatientsPatientIdRoute,
  AppVisitsVisitIdRoute: AppVisitsVisitIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
  AppVisitsIndexRoute: AppVisitsIndexRoute,
  AppAdminTenantsTenantIdRoute: AppAdminTenantsTenantIdRoute,
  AppAdminTenantsIndexRoute: AppAdminTenantsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
